import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'sdk-architecture',
    'supported-content-types',
    {
      type: 'category',
      label: 'Android',
      link: {
        type: 'generated-index',
        description:
          'Integrate FLOWER SDK into Android applications. Supports DTH/Multicast and Unicast (HLS/DASH) delivery for Linear TV & FAST, VOD, and advanced ad formats.',
      },
      items: [{type: 'autogenerated', dirName: 'android'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Web / Smart TV',
      link: {
        type: 'generated-index',
        description:
          'Integrate FLOWER SDK into browser-based players and Smart TV platforms (Tizen, webOS, etc.) using HLS.js.',
      },
      items: [{type: 'autogenerated', dirName: 'web-smart-tv'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'iOS',
      link: {
        type: 'generated-index',
        description:
          'Integrate FLOWER SDK into iOS and tvOS applications using AVPlayer.',
      },
      items: [{type: 'autogenerated', dirName: 'ios'}],
      collapsed: true,
    },
  ],
};

export default sidebars;
