import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'For Linear TV (Multicast, DTH)',
      link: {
        type: 'generated-index',
        description:
          'The FLOWER SDK for TV allows you to easily integrate personalized ads into any ad placements within your TV app, such as those used for linear TV and VOD platforms.\n\nThe SDK communicates with the ad server as needed, downloads relevant ads for the user, stores them in local storage, and interacts with your TV app\'s media playback module to provide a seamless viewing experience.\n\nThis guide explains how to integrate ad operation functions into your TV app and use the SDK to play ad creatives.',
      },
      items: [{type: 'autogenerated', dirName: 'linear-tv'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'For OTT/FAST',
      link: {
        type: 'generated-index',
        description: 'The FLOWER SDK for OTT/FAST allows you to deliver ads into live streams, VOD content, and web/app environments.',
      },
      items: [{type: 'autogenerated', dirName: 'ott-fast'}],
      collapsed: true,
    },
  ],
};

export default sidebars;
