import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'SDK Architecture',
      link: {type: 'doc', id: 'sdk-architecture/index'},
      items: [
        'sdk-architecture/ott-linear-tv-fast-ads',
        'sdk-architecture/vod-ads',
        'sdk-architecture/advanced-ad-formats',
      ],
    },
    'supported-content-types',
    {
      type: 'category',
      label: 'Android',
      link: {
        type: 'generated-index',
        description:
          'Integrate FLOWER SDK into Android applications. Supports Unicast (HLS/DASH) delivery for Linear TV (incl. FAST), VOD, and advanced ad formats. For satellite (DTH) and IPTV multicast, see the Satellite/IPTV section.',
      },
      items: [{type: 'autogenerated', dirName: 'android'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Web / Smart TV',
      link: {
        type: 'generated-index',
        description:
          'Integrate the FLOWER SDK into HTML5-based web browsers and Smart TV platforms (Tizen, webOS, etc.).',
      },
      items: [{type: 'autogenerated', dirName: 'web-smart-tv'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'iOS',
      link: {
        type: 'generated-index',
        description:
          'Integrate the FLOWER SDK into iOS and tvOS applications.',
      },
      items: [{type: 'autogenerated', dirName: 'ios'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Satellite/IPTV',
      link: {
        type: 'generated-index',
        description:
          'Integrates replacement ads using DTMF cue tones or SCTE-35 in satellite (DTH) and IPTV multicast broadcast environments.',
      },
      items: [{type: 'autogenerated', dirName: 'satellite-iptv'}],
      collapsed: true,
    },
  ],
};

export default sidebars;
